spring:
  application:
    name: currency-rate
  data:
    redis:
      host: localhost
      port: 6379
      password: 88888888

api:
  exchangerate:
    url: https://api.exchangerate.host
    key: c88585ec17bf7113e4347b03b8e35780

application:
#  Choose source of exchange rates here. Supported values: exchangerate
  source: exchangerate
#  Time before redis will clean row for specific key
  redis:
    ttl: 1m


